apiVersion: events.k8s.io/v1
deprecatedCount: 2
deprecatedFirstTimestamp: "2023-03-08T11:45:16Z"
deprecatedLastTimestamp: "2023-03-08T11:55:19Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-master-2.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:45:30Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T11:55:19Z"
  name: cloud-network-config-controller-79d5dd8fcb-24qk4.174a6f0dcc811f8a
  namespace: openshift-cloud-network-config-controller
  resourceVersion: "22590"
  uid: 33e9b7a0-b27f-45ec-89f7-20e7d4805399
note: Started container controller
reason: Started
regarding:
  apiVersion: v1
  fieldPath: spec.containers{controller}
  kind: Pod
  name: cloud-network-config-controller-79d5dd8fcb-24qk4
  namespace: openshift-cloud-network-config-controller
  resourceVersion: "3818"
  uid: 9c3e04b0-5750-4faa-a6c2-85bec74f951c
type: Normal
