apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-03-08T11:46:43Z"
deprecatedLastTimestamp: "2023-03-08T11:46:43Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-master-2.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:46:43Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T11:46:43Z"
  name: openshift-config-operator-6cd8ffb884-2ck28.174a6f2222cbfcac
  namespace: openshift-config-operator
  resourceVersion: "9583"
  uid: 331da79a-3af3-4b16-ae00-cb13a9170ca5
note: Container image "registry.ci.openshift.org/origin/4.12-2023-03-04-063026@sha256:fbc0cf0b8d2d8c1986c51b7dce88f36b33d6ff4a742d42e91edbae0b48b6991f"
  already present on machine
reason: Pulled
regarding:
  apiVersion: v1
  fieldPath: spec.containers{openshift-config-operator}
  kind: Pod
  name: openshift-config-operator-6cd8ffb884-2ck28
  namespace: openshift-config-operator
  resourceVersion: "3800"
  uid: 09ee5400-bdd3-4460-be99-859f41444c9c
type: Normal
