apiVersion: events.k8s.io/v1
deprecatedCount: 2
deprecatedFirstTimestamp: "2023-03-08T11:45:15Z"
deprecatedLastTimestamp: "2023-03-08T11:46:43Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-master-2.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:45:28Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T11:46:43Z"
  name: openshift-config-operator-6cd8ffb884-2ck28.174a6f0dbb75487f
  namespace: openshift-config-operator
  resourceVersion: "9599"
  uid: c59fc6c2-317f-484a-a4b1-29f7f46001d3
note: Started container openshift-config-operator
reason: Started
regarding:
  apiVersion: v1
  fieldPath: spec.containers{openshift-config-operator}
  kind: Pod
  name: openshift-config-operator-6cd8ffb884-2ck28
  namespace: openshift-config-operator
  resourceVersion: "3800"
  uid: 09ee5400-bdd3-4460-be99-859f41444c9c
type: Normal
