apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-03-08T11:51:16Z"
deprecatedLastTimestamp: "2023-03-08T11:51:16Z"
deprecatedSource:
  component: node-controller
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:51:16Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: kube-controller-manager
    operation: Update
    time: "2023-03-08T11:51:16Z"
  name: machine-config-server-q86d6.174a6f61c8e977fd
  namespace: openshift-machine-config-operator
  resourceVersion: "17016"
  uid: 99a6de3a-7f70-479e-bec7-59a0b499e0ab
note: Node is not ready
reason: NodeNotReady
regarding:
  apiVersion: v1
  kind: Pod
  name: machine-config-server-q86d6
  namespace: openshift-machine-config-operator
  resourceVersion: "8103"
  uid: de5725e4-6518-4d9f-9237-09aff5c7d381
type: Warning
