apiVersion: events.k8s.io/v1
deprecatedCount: 2
deprecatedFirstTimestamp: "2023-03-08T11:46:06Z"
deprecatedLastTimestamp: "2023-03-08T11:55:11Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-master-0.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:46:06Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T11:55:13Z"
  name: machine-config-controller-7d66fd8577-4xdqg.174a6f19723a081b
  namespace: openshift-machine-config-operator
  resourceVersion: "22422"
  uid: fea02786-195c-4fba-9dfc-76b510a273f6
note: Created container machine-config-controller
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{machine-config-controller}
  kind: Pod
  name: machine-config-controller-7d66fd8577-4xdqg
  namespace: openshift-machine-config-operator
  resourceVersion: "7959"
  uid: 0b0c24c7-2c8f-4b7b-9c60-e3310302bfe3
type: Normal
