apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-03-08T12:01:50Z"
deprecatedLastTimestamp: "2023-03-08T12:01:50Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-worker-b-5rcfz.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T12:01:50Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T12:01:50Z"
  name: alertmanager-main-0.174a6ff56882e1c1
  namespace: openshift-monitoring
  resourceVersion: "28614"
  uid: 130e053b-c624-4a27-ba03-dc01cf4f82ed
note: Container image "registry.ci.openshift.org/origin/4.12-2023-03-04-063026@sha256:ff07afaff7fff38e3124162c5791ba969bcd750be02d5878f0387aed62517fa9"
  already present on machine
reason: Pulled
regarding:
  apiVersion: v1
  fieldPath: spec.containers{kube-rbac-proxy}
  kind: Pod
  name: alertmanager-main-0
  namespace: openshift-monitoring
  resourceVersion: "28591"
  uid: ed3b89ac-04c7-4465-ab7d-bb182af3d371
type: Normal
