apiVersion: events.k8s.io/v1
deprecatedCount: 1
deprecatedFirstTimestamp: "2023-03-08T11:48:42Z"
deprecatedLastTimestamp: "2023-03-08T11:48:42Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-master-2.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:48:42Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T11:48:42Z"
  name: ingress-operator-7479db4746-9h6ll.174a6f3deee96e35
  namespace: openshift-ingress-operator
  resourceVersion: "12529"
  uid: 6fe66e39-5d7f-46fb-8be7-f18d76a09d1b
note: Container image "registry.ci.openshift.org/origin/4.12-2023-03-04-063026@sha256:b79ae5b794a95f814a3454c300ec678169285167f9f117d1465f7ad8f4cb4806"
  already present on machine
reason: Pulled
regarding:
  apiVersion: v1
  fieldPath: spec.containers{ingress-operator}
  kind: Pod
  name: ingress-operator-7479db4746-9h6ll
  namespace: openshift-ingress-operator
  resourceVersion: "3811"
  uid: 39841c1d-6137-4a34-b24a-0aab2a04577e
type: Normal
