apiVersion: events.k8s.io/v1
deprecatedCount: 3
deprecatedFirstTimestamp: "2023-03-08T11:46:22Z"
deprecatedLastTimestamp: "2023-03-08T11:51:29Z"
deprecatedSource:
  component: kubelet
  host: vrutkovs-mrmwt-master-2.c.openshift-gce-devel.internal
eventTime: null
kind: Event
metadata:
  creationTimestamp: "2023-03-08T11:46:26Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
        f:host: {}
      f:type: {}
    manager: kubelet
    operation: Update
    time: "2023-03-08T11:51:29Z"
  name: ingress-operator-7479db4746-9h6ll.174a6f1d2b4f0ab1
  namespace: openshift-ingress-operator
  resourceVersion: "17211"
  uid: d730d161-ec57-44a2-9ae8-6c470dbdece4
note: Created container ingress-operator
reason: Created
regarding:
  apiVersion: v1
  fieldPath: spec.containers{ingress-operator}
  kind: Pod
  name: ingress-operator-7479db4746-9h6ll
  namespace: openshift-ingress-operator
  resourceVersion: "3811"
  uid: 39841c1d-6137-4a34-b24a-0aab2a04577e
type: Normal
